### ISSUE TITLE
pcap can not get deviceIndex using OpenLive() on Windows 10

### ISSUE THREAD

**Issue by ChenYahui2019** [google/gopacket#661] opened 2019-06-04 03:11 UTC
The function `pcap.OpenLive` on Windows cannot get `deviceIndex` of device, because the first parameter `device` looks like `\Device\NPF_{E6D15D75-CA01-40D5-8415-796AACDD4D0A}` leading to `net.InterfaceByName(device)` return err on Windows 10.

```
func OpenLive(device string, snaplen int32, promisc bool, timeout time.Duration) (handle *Handle, _ error) {
	var pro int
	if promisc {
		pro = 1
	}

	p, err := pcapOpenLive(device, int(snaplen), pro, timeoutMillis(timeout))
	if err != nil {
		return nil, err
	}
	p.timeout = timeout
	p.device = device

	ifc, err := net.InterfaceByName(device)  // _return error here_
	if err != nil {
		// The device wasn't found in the OS, but could be "any"
		// Set index to 0
		p.deviceIndex = 0
	} else {
		p.deviceIndex = ifc.Index
	}
```

**Comment by notti** [comment] 2019-06-10 09:07
Duplicate of #456

**Closed by notti** 2019-06-10 09:07 UTC

**Comment by akkuman** [comment] 2019-07-09 10:11
use pcap.FindAllDevs() can get the name which contains "Device\NPF_"

**Comment by blacklat** [comment] 2020-02-20 17:02
> use pcap.FindAllDevs() can get the name which contains "Device\NPF_"

It doesn't help at all, the OpenLive function only accepts one device at a time, which is ridiculous...

**Comment by lylest** [comment] 2024-03-18 13:46
This guide has helped me solve this issue https://haydz.github.io/2020/07/06/Go-Windows-NIC.html

**Comment by malipense** [comment] 2024-04-15 23:15
> This guide has helped me solve this issue https://haydz.github.io/2020/07/06/Go-Windows-NIC.html

Thank you sir!
