### ISSUE TITLE
libpcap performance regression from 7d9ba85c47bb41298fed10f5769f793741de187f

### ISSUE THREAD

**Issue by jimmystewpot** [google/gopacket#339] opened 2017-08-29 23:14 UTC
Hello,

We have recently seen a performance regression when using gopacket's pcap capabilities. We noticed the regression when we saw the number of packets being processed dropped significantly. When we investigated further we identified that the pcap handle Stats() was reporting Dropped to be around 98% of the total packets processed.

When we started to investigate the issue we rolled back the commits on gopacket and found that the regression was introduced in commit 7d9ba85c47bb41298fed10f5769f793741de187f

Here is the statistics output.
```
Aug 28 22:18:06 time="2017-08-28T22:18:06Z" level=info msg="Statistics received: 2480538, dropped: 0, interface dropped 0"
Aug 28 22:18:21 time="2017-08-28T22:18:21Z" level=info msg="Statistics received: 2480630, dropped: 0, interface dropped 0"
Aug 28 22:18:36 time="2017-08-28T22:18:36Z" level=info msg="Statistics received: 2480726, dropped: 0, interface dropped 0"
Aug 28 22:18:51 time="2017-08-28T22:18:51Z" level=info msg="Statistics received: 2480812, dropped: 0, interface dropped 0"
Aug 28 22:19:06 time="2017-08-28T22:19:06Z" level=info msg="Statistics received: 2480884, dropped: 0, interface dropped 0"
Aug 28 22:19:21 time="2017-08-28T22:19:21Z" level=info msg="Statistics received: 2480972, dropped: 0, interface dropped 0"
<<< REDEPLOY WITH NEW VERSION OF gopacket >>>
Aug 28 22:20:03 time="2017-08-28T22:20:03Z" level=info msg="Statistics received: 64, dropped: 36, interface dropped 0"
Aug 28 22:20:18 time="2017-08-28T22:20:18Z" level=info msg="Statistics received: 150, dropped: 122, interface dropped 0"
Aug 28 22:20:33 time="2017-08-28T22:20:33Z" level=info msg="Statistics received: 230, dropped: 202, interface dropped 0"
Aug 28 22:20:48 time="2017-08-28T22:20:48Z" level=info msg="Statistics received: 326, dropped: 298, interface dropped 0"
Aug 28 22:21:03 time="2017-08-28T22:21:03Z" level=info msg="Statistics received: 402, dropped: 374, interface dropped 0"
Aug 28 22:21:18 time="2017-08-28T22:21:18Z" level=info msg="Statistics received: 488, dropped: 460, interface dropped 0"
Aug 28 22:21:33 time="2017-08-28T22:21:33Z" level=info msg="Statistics received: 566, dropped: 538, interface dropped 0"
Aug 28 22:21:48 time="2017-08-28T22:21:48Z" level=info msg="Statistics received: 654, dropped: 626, interface dropped 0"
Aug 28 22:22:03 time="2017-08-28T22:22:03Z" level=info msg="Statistics received: 732, dropped: 704, interface dropped 0"
Aug 28 22:22:18 time="2017-08-28T22:22:18Z" level=info msg="Statistics received: 796, dropped: 768, interface dropped 0"
Aug 28 22:22:33 time="2017-08-28T22:22:33Z" level=info msg="Statistics received: 876, dropped: 848, interface dropped 0"
Aug 28 22:22:48 time="2017-08-28T22:22:48Z" level=info msg="Statistics received: 966, dropped: 938, interface dropped 0"
Aug 28 22:23:03 time="2017-08-28T22:23:03Z" level=info msg="Statistics received: 1046, dropped: 1018, interface dropped 0"
Aug 28 22:23:18 time="2017-08-28T22:23:18Z" level=info msg="Statistics received: 1102, dropped: 1074, interface dropped 0"
```

From the logs we can see that when we redeployed with the latest commits the number of drops started to increase. When we then reverted back to the previous binary the drops returned to zero. We then started to investigate and found that the problem was only introduced in the commit listed above.

System Info
```
hostname:~# go version
go version go1.8.3 linux/amd64

hostname:~# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial

hostname:~# dpkg --list | grep pcap
ii  libpcap-dev                       1.7.4-2                                    all          development library for libpcap (transitional package)
ii  libpcap0.8:amd64                  1.7.4-2                                    amd64        system interface for user-level packet capture
ii  libpcap0.8-dev                    1.7.4-2                                    amd64        development library and header files for libpcap0.8
```

**Comment by gconnell** [comment] 2017-09-12 20:44
Could you sync to master and retry?  A fix that went in today may have a fix for you.

**Comment by negbie** [comment] 2017-09-18 13:35
Same problem for me. CPU usage went up by factor 6. Commit 92028c3b3f02c1ff69b17058a2302ba1bb44b16f did not change anything.

**Comment by negbie** [comment] 2017-09-18 14:47
Issue seems to be inside pcap_unix.go openLive() function

**Comment by negbie** [comment] 2017-09-18 15:06
Ok when I change the timeout from
pcap.OpenLive(sniffer.config.Device, int32(sniffer.config.Snaplen), true, 500*time.Millisecond)
to
pcap.OpenLive(sniffer.config.Device, int32(sniffer.config.Snaplen), true, pcap.BlockForever)

all is looking fine again.

**Comment by gconnell** [comment] 2017-09-18 16:48
Hmm, this is a pretty big smoking gun.  Could you let me know what method you're using to get packets?  Are you calling the `gopacket.PacketSource.Packets()` function?  Or calling `pcap.Handle.ReadPacketData`directly?

**Comment by negbie** [comment] 2017-09-18 17:04
I use

type SnifferSetup struct {
...
DataSource gopacket.PacketDataSource
...
}
...
data, ci, err := sniffer.DataSource.ReadPacketData()

**Comment by jimmystewpot** [comment] 2017-09-20 01:51
```
pcap.OpenLive(config.device, config.snapLen, true, pcap.BlockForever)
```
Is our specific code block for the capture. I have been unable to test the specific patch yet, i will get onto that in the next few days.

**Comment by gconnell** [comment] 2017-09-28 16:12
https://github.com/google/gopacket/pull/357 looks like it might also be a fix for this, if you want to pull in the current master and see if it fixes things.

**Comment by jcrussell** [comment] 2017-11-01 17:08
Doesn't look like this was fixed by #357. From pprof:
```
    0     0%     0%     29.53s 93.21%  pcap.(*Handle).ReadPacketData github.com/google/gopacket/pcap/pcap.go
0.19s   0.6%   0.6%     29.53s 93.21%  pcap.(*Handle).getNextBufPtrLocked github.com/google/gopacket/pcap/pcap.go
0.83s  2.62%  3.22%     29.34s 92.61%  pcap.(*Handle).getNextBufPtrLocked.func1 github.com/google/gopacket/pcap/pcap.go
0.18s  0.57%  3.79%     19.45s 61.40%  pcap._Cfunc_pcap_next_ex github.com/google/gopacket/pcap/_obj/_cgo_gotypes.go
```

**Comment by jcrussell** [comment] 2017-11-01 17:59
Seems related to 92028c3b:

```
For PCAP, we should:

1) if we have a timeout, return an error when that timeout has been hit
and no packet received.
2) if we have a negative timeout, loop forever waiting for a packet,
checking every -timeout.
```

If the timeout is `pcap.BlockForever` then it checks for packets every 10ms (not using the "block indefinitely select in `pcap_wait` anymore).
If the timeout is greater than zero, then we immediately try to read another packet (missing return?).

I can try to work on a patch to see if I can fix this.

**Comment by gconnell** [comment] 2017-11-01 19:56
Agreed, that was the behavior we were aiming for.  Any help in getting back to this state greatly appreciated :)

**Comment by gconnell** [comment] 2017-11-01 19:57
Oh, one note:  If we have a negative timeout but we hit a non-timeout-exceeded error, we should break out and return that.

**Comment by jcrussell** [comment] 2017-11-02 16:15
Can you test again with master?

@jimmystewpot @negbie @JustinAzoff

**Comment by negbie** [comment] 2017-11-02 16:45
Hi,
I checked out master and changed "pcap.BlockForever" to "5*time.Minute".
I can confirm that your commit fixed this issue for me. Thank you!

**Comment by JustinAzoff** [comment] 2017-11-02 21:04
Things look great for me using pcap.BlockForever.

**Comment by jimmystewpot** [comment] 2018-02-21 00:34
Agree, this can be closed.

**Closed** 2018-02-21 00:44 UTC
