### ISSUE TITLE
Getting ERROR:  serializing resource record of type Unknown not supported for ARCount 1 and Additionals.

### ISSUE THREAD

**Issue by sidheshdivekar29** [google/gopacket#509] opened 2018-09-04 17:18 UTC
I am overwriting dns response sent by 8.8.8.8 for www.cnbc.com and then trying to serialize.
I empty out the dns response and add my custom dns RR in answer section. 
This works with "nslookup www.cnbc.com 8.8.8.8" however it fails with "dig @8.8.8.8 www.cnbc.com"

With dig I see that ARCount is 1 and there is Additionals set, Additionals:[{Name:[] Type:Unknown Class:Unknown TTL:0 DataLength:0 Data:[] IP:<nil> NS:[] CNAME:[] PTR:[] TXTs:[] SOA:{MName:[] RName:[] Serial:0 Refresh:0 Retry:0 Expire:0 Minimum:0} SRV:{Priority:0 Weight:0 Port:0 Name:[]} MX:{Preference:0 Name:[]} TXT:[]}]
I don't see that in case of nslookup

Below is the ip byte array of dns response. If you parse this using NewDecodingLayerParser
	parser := gopacket.NewDecodingLayerParser(LayerTypeIPv4, &ip4,
		&ip6, &udp, &dns)

You would get the dns structure which is pasted above.

[69 0 0 158 1 135 0 0 117 17 20 180 8 8 8 8 30 1 1 4 0 53 216 228 0 138 161 197 208 87 129 128 0 1 0 3 0 0 0 1 3 119 119 119 4 99 110 98 99 3 99 111 109 0 0 1 0 1 192 12 0 5 0 1 0 0 49 31 0 26 3 119 119 119 4 99 110 98 99 3 99 111 109 7 101 100 103 101 107 101 121 3 110 101 116 0 192 42 0 5 0 1 0 0 48 172 0 23 5 101 51 51 54 53 3 101 49 50 10 97 107 97 109 97 105 101 100 103 101 192 63 192 80 0 1 0 1 0 0 0 19 0 4 23 72 194 157 0 0 41 2 0 0 0 0 0 0 0]

**Comment by notti** [comment] 2018-11-04 20:38
dig uses EDNS0 (RFC 2671) by default. This is what you see with the ARCount 1 and the additional record [0 0 41 2 0 0 0 0 0 0 0] (first 0: root, 0 41: type 41 = OPT, 2 0: payload size 512, ...) at the end.
EDNS is not implemented in gopacket (yet). That's why this doesn't work.

**Comment by notti** [comment] 2018-11-04 20:38
Duplicate of #184

**Closed** 2018-11-04 20:38 UTC
