### ISSUE TITLE
Issue with crafting TCP packets - incorrect calculation for packets length

### ISSUE THREAD

**Issue by pavel-odintsov** [google/gopacket#378] opened 2017-10-26 00:20 UTC
Hello!

Thanks for your great library! I managed to craft DNS inside UDP over IPv4 and IPv6 protocols. Works great!

But I hit some strange issues and suppose some bug in TCP crafting code.

I use the following code to create TCP packet on top of IPv4 protocol:
```        
// Let's craft network packets
buf := gopacket.NewSerializeBuffer()

opts := gopacket.SerializeOptions{
    FixLengths: true,
}

ethernetLayer := &layers.Ethernet{
    SrcMAC: []byte{0, 0, 0, 0, 0, 0},
    DstMAC: []byte{0, 0, 0, 0, 0, 0},
}

ethernetLayer.EthernetType = layers.EthernetTypeIPv4

ipv4 := &layers.IPv4{
    Version: 4,
    SrcIP:   srcIPv4Slice,
    DstIP:   dstIPv4Slice,
    TTL:     128,
}   

 ipv4.Protocol = layers.IPProtocolTCP

gopacket.SerializeLayers(buf, opts,
     ethernetLayer,
     ipv4,
     &layers.TCP{
         SrcPort: layers.TCPPort(srcPort),
         DstPort: layers.TCPPort(dstPort),
         SYN:     true,
         ACK:     true,
    },  
    gopacket.Payload(dnsBuffer)
)

w.Write(buf.Bytes())
```

Where dnsBuffer is a properly created DNS message. usually, they're about 50 bytes.

But it crafts packets with really strange length:
```
sudo tcpdump -n -r /tmp/result.pcap 
reading from file /tmp/result.pcap, link-type EN10MB (Ethernet)
01:06:21.000000 IP xxxx.60677 > xxxx.53: Flags [S.], seq 0:37, ack 0, win 0, length 37256 [b2&3=0x1] [0q] [887au] (35)
18:04:25.000000 IP xxxx.50511 > xxxx.53: Flags [S.], seq 0:46, ack 0, win 0, length 46256 [b2&3=0x1] [0q] [631au] (44)
```

And tshark output:
```
sudo tshark -o tcp.desegment_tcp_streams:false -n -r /tmp/result.pcap 
Running as user "root" and group "root". This could be dangerous.
  1   0.000000 xxxx -> xxxx  DNS 91 Standard query 0x0100 [Packet size limited during capture]
  2 147484.000000 xxxx -> xxxx  DNS 100 Standard query 0x0100 [Packet size limited during capture]
```

Detailed tshark output:
```
Frame 1: 91 bytes on wire (728 bits), 91 bytes captured (728 bits)
    Encapsulation type: Ethernet (1)
    Arrival Time: Sep 19, 2017 01:06:21.000000000 BST
    [Time shift for this packet: 0.000000000 seconds]
    Epoch Time: 1505779581.000000000 seconds
    [Time delta from previous captured frame: 0.000000000 seconds]
    [Time delta from previous displayed frame: 0.000000000 seconds]
    [Time since reference or first frame: 0.000000000 seconds]
    Frame Number: 1
    Frame Length: 91 bytes (728 bits)
    Capture Length: 91 bytes (728 bits)
    [Frame is marked: False]
    [Frame is ignored: False]
    [Protocols in frame: eth:ethertype:ip:tcp:dns]
Ethernet II, Src: 00:00:00:00:00:00 (00:00:00:00:00:00), Dst: 00:00:00:00:00:00 (00:00:00:00:00:00)
    Destination: 00:00:00:00:00:00 (00:00:00:00:00:00)
        Address: 00:00:00:00:00:00 (00:00:00:00:00:00)
        .... ..0. .... .... .... .... = LG bit: Globally unique address (factory default)
        .... ...0 .... .... .... .... = IG bit: Individual address (unicast)
    Source: 00:00:00:00:00:00 (00:00:00:00:00:00)
        Address: 00:00:00:00:00:00 (00:00:00:00:00:00)
        .... ..0. .... .... .... .... = LG bit: Globally unique address (factory default)
        .... ...0 .... .... .... .... = IG bit: Individual address (unicast)
    Type: IP (0x0800)
Internet Protocol Version 4, Src: x (x), Dst: x (x)
    Version: 4
    Header Length: 20 bytes
    Differentiated Services Field: 0x00 (DSCP 0x00: Default; ECN: 0x00: Not-ECT (Not ECN-Capable Transport))
        0000 00.. = Differentiated Services Codepoint: Default (0x00)
        .... ..00 = Explicit Congestion Notification: Not-ECT (Not ECN-Capable Transport) (0x00)
    Total Length: 77
    Identification: 0x0000 (0)
    Flags: 0x00
        0... .... = Reserved bit: Not set
        .0.. .... = Don't fragment: Not set
        ..0. .... = More fragments: Not set
    Fragment offset: 0
    Time to live: 128
    Protocol: TCP (6)
    Header checksum: 0x0000 [validation disabled]
        [Good: False]
        [Bad: False]
    Source: x (x)
    Destination: x (x)
    [Source GeoIP: Unknown]
    [Destination GeoIP: Unknown]
Transmission Control Protocol, Src Port: 60677 (60677), Dst Port: 53 (53), Seq: 0, Ack: 1, Len: 37
    Source Port: 60677 (60677)
    Destination Port: 53 (53)
    [Stream index: 0]
    [TCP Segment Len: 37]
    Sequence number: 0    (relative sequence number)
    [Next sequence number: 37    (relative sequence number)]
    Acknowledgment number: 1    (relative ack number)
    Header Length: 20 bytes
    .... 0000 0001 0010 = Flags: 0x012 (SYN, ACK)
        000. .... .... = Reserved: Not set
        ...0 .... .... = Nonce: Not set
        .... 0... .... = Congestion Window Reduced (CWR): Not set
        .... .0.. .... = ECN-Echo: Not set
        .... ..0. .... = Urgent: Not set
        .... ...1 .... = Acknowledgment: Set
        .... .... 0... = Push: Not set
        .... .... .0.. = Reset: Not set
        .... .... ..1. = Syn: Set
            [Expert Info (Chat/Sequence): Connection establish acknowledge (SYN+ACK): server port 60677]
                [Connection establish acknowledge (SYN+ACK): server port 60677]
                [Severity level: Chat]
                [Group: Sequence]
        .... .... ...0 = Fin: Not set
    Window size value: 0
    [Calculated window size: 0]
    Checksum: 0x0000 [validation disabled]
        [Good Checksum: False]
        [Bad Checksum: False]
    Urgent pointer: 0
    [SEQ/ACK analysis]
        [Bytes in flight: 38]
Domain Name System (query)
    Length: 35546
    Transaction ID: 0x0100
    Flags: 0x0001 Standard query
        0... .... .... .... = Response: Message is a query
        .000 0... .... .... = Opcode: Standard query (0)
        .... ..0. .... .... = Truncated: Message is not truncated
        .... ...0 .... .... = Recursion desired: Don't do query recursively
        .... .... .0.. .... = Z: reserved (0)
        .... .... ...0 .... = Non-authenticated data: Unacceptable
    Questions: 0
    Answer RRs: 0
    Authority RRs: 0
    Additional RRs: 887
    Additional records
[Packet size limited during capture: DNS truncated]

Frame 2: 100 bytes on wire (800 bits), 100 bytes captured (800 bits)
    Encapsulation type: Ethernet (1)
    Arrival Time: Sep 20, 2017 18:04:25.000000000 BST
    [Time shift for this packet: 0.000000000 seconds]
    Epoch Time: 1505927065.000000000 seconds
    [Time delta from previous captured frame: 147484.000000000 seconds]
    [Time delta from previous displayed frame: 147484.000000000 seconds]
    [Time since reference or first frame: 147484.000000000 seconds]
    Frame Number: 2
    Frame Length: 100 bytes (800 bits)
    Capture Length: 100 bytes (800 bits)
    [Frame is marked: False]
    [Frame is ignored: False]
    [Protocols in frame: eth:ethertype:ip:tcp:dns]
Ethernet II, Src: 00:00:00:00:00:00 (00:00:00:00:00:00), Dst: 00:00:00:00:00:00 (00:00:00:00:00:00)
    Destination: 00:00:00:00:00:00 (00:00:00:00:00:00)
        Address: 00:00:00:00:00:00 (00:00:00:00:00:00)
        .... ..0. .... .... .... .... = LG bit: Globally unique address (factory default)
        .... ...0 .... .... .... .... = IG bit: Individual address (unicast)
    Source: 00:00:00:00:00:00 (00:00:00:00:00:00)
        Address: 00:00:00:00:00:00 (00:00:00:00:00:00)
        .... ..0. .... .... .... .... = LG bit: Globally unique address (factory default)
        .... ...0 .... .... .... .... = IG bit: Individual address (unicast)
    Type: IP (0x0800)
Internet Protocol Version 4, Src: x (x), Dst: x (x)
    Version: 4
    Header Length: 20 bytes
    Differentiated Services Field: 0x00 (DSCP 0x00: Default; ECN: 0x00: Not-ECT (Not ECN-Capable Transport))
        0000 00.. = Differentiated Services Codepoint: Default (0x00)
        .... ..00 = Explicit Congestion Notification: Not-ECT (Not ECN-Capable Transport) (0x00)
    Total Length: 86
    Identification: 0x0000 (0)
    Flags: 0x00
        0... .... = Reserved bit: Not set
        .0.. .... = Don't fragment: Not set
        ..0. .... = More fragments: Not set
    Fragment offset: 0
    Time to live: 128
    Protocol: TCP (6)
    Header checksum: 0x0000 [validation disabled]
        [Good: False]
        [Bad: False]
    Source: xxx
    Destination: xxx
    [Source GeoIP: Unknown]
    [Destination GeoIP: Unknown]
Transmission Control Protocol, Src Port: 50511 (50511), Dst Port: 53 (53), Seq: 0, Ack: 1, Len: 46
    Source Port: 50511 (50511)
    Destination Port: 53 (53)
    [Stream index: 1]
    [TCP Segment Len: 46]
    Sequence number: 0    (relative sequence number)
    [Next sequence number: 46    (relative sequence number)]
    Acknowledgment number: 1    (relative ack number)
    Header Length: 20 bytes
    .... 0000 0001 0010 = Flags: 0x012 (SYN, ACK)
        000. .... .... = Reserved: Not set
        ...0 .... .... = Nonce: Not set
        .... 0... .... = Congestion Window Reduced (CWR): Not set
        .... .0.. .... = ECN-Echo: Not set
        .... ..0. .... = Urgent: Not set
        .... ...1 .... = Acknowledgment: Set
        .... .... 0... = Push: Not set
        .... .... .0.. = Reset: Not set
        .... .... ..1. = Syn: Set
            [Expert Info (Chat/Sequence): Connection establish acknowledge (SYN+ACK): server port 50511]
                [Connection establish acknowledge (SYN+ACK): server port 50511]
                [Severity level: Chat]
                [Group: Sequence]
        .... .... ...0 = Fin: Not set
    Window size value: 0
    [Calculated window size: 0]
    Checksum: 0x0000 [validation disabled]
        [Good Checksum: False]
        [Bad Checksum: False]
    Urgent pointer: 0
    [SEQ/ACK analysis]
        [Bytes in flight: 47]
Domain Name System (query)
    Length: 48181
    Transaction ID: 0x0100
    Flags: 0x0001 Standard query
        0... .... .... .... = Response: Message is a query
        .000 0... .... .... = Opcode: Standard query (0)
        .... ..0. .... .... = Truncated: Message is not truncated
        .... ...0 .... .... = Recursion desired: Don't do query recursively
        .... .... .0.. .... = Z: reserved (0)
        .... .... ...0 .... = Non-authenticated data: Unacceptable
    Questions: 0
    Answer RRs: 0
    Authority RRs: 0
    Additional RRs: 631
    Additional records
[Packet size limited during capture: DNS truncated]
```

Could you help me? I could provide pcap or any other debug information.

**Comment by florianl** [comment] 2017-10-26 18:18
In Frame 1 there are 887 Additional RRs and in Frame 2 631. is this intended behavior?

**Comment by gconnell** [comment] 2017-10-26 19:29
Hmm, weird.  Could you dump out dnsBuffer and paste it in:

fmt.Printf("DNS: %x\n", dnsBuffer)

**Comment by pavel-odintsov** [comment] 2017-11-07 12:43
[dump.pcap.zip](https://github.com/google/gopacket/files/1449990/dump.pcap.zip)

**Comment by pavel-odintsov** [comment] 2017-11-07 13:02
I tried to add window size and change flags to PSH:
```
                               PSH:        true,
                               Window:     uint16(len(dnsBuffer)),
                               DataOffset: 0,
```

But it does not help at all :(

**Comment by pavel-odintsov** [comment] 2017-11-07 13:28
I extracted all logic and prepared clear reproduce code: https://gist.github.com/pavel-odintsov/b5bcd59dbb8e189d7f129e81faf969c7 

It works this way:
```
bin/example_tcp 
2017/11/07 13:27:28 DNS message: ;; opcode: QUERY, status: NOERROR, id: 25354
;; flags: rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;testdomain.com.	IN	 A
2017/11/07 13:27:28 dnsBuffer: [99 10 1 0 0 1 0 0 0 0 0 0 10 116 101 115 116 100 111 109 97 105 110 3 99 111 109 0 0 1 0 1] length: 32
2017/11/07 13:27:28 Dump generated at: /tmp/dump.pcap
```

And produced pcap with same issue:
```
vagrant@debian-jessie:root_dns_ditl$ sudo tcpdump -r /tmp/dump.pcap -n -v
reading from file /tmp/dump.pcap, link-type EN10MB (Ethernet)
13:28:00.623302 IP (tos 0x0, ttl 128, id 0, offset 0, flags [none], proto TCP (6), length 72, bad cksum 0 (->3cae)!)
    127.0.0.1.65111 > 127.0.0.1.53: Flags [P], cksum 0x0000 (incorrect -> 0xf11f), seq 0:32, win 32, length 32256 [b2&3=0x1] [0q] [2676au] (30)
vagrant@debian-jessie:root_dns_ditl$ sudo tcpdump -r /tmp/dump.pcap -n 
reading from file /tmp/dump.pcap, link-type EN10MB (Ethernet)
13:28:00.623302 IP 127.0.0.1.65111 > 127.0.0.1.53: Flags [P], seq 0:32, win 32, length 32256 [b2&3=0x1] [0q] [2676au] (30)
```

**Comment by florianl** [comment] 2017-11-22 20:17
I had a look into the two tcp packets, you provided in dump.pcap.zip.
`
$ tcpdump -n -r dump.pcap
reading from file dump.pcap, link-type EN10MB (Ethernet)
01:06:21.000000 IP 127.0.0.1.60677 > 127.0.0.1.domain: Flags [S.], seq 0:32, ack 0, win 0, length 32256 [b2&3=0x1] [0q] [2676au] (30)
01:10:38.000000 IP 127.0.0.1.61748 > 127.0.0.1.domain: Flags [S.], seq 0:32, ack 0, win 0, length 32256 [b2&3=0x1] [0q] [2676au] (30)
`
But if I take a look into this dump with wireshark-gtk is shows me a length of 72 bytes in the IP header for both packets. At the corresponding byte position I find `0x48` in both packets. 

Can you provide a full working code example that might produce wrong output?

**Comment by pavel-odintsov** [comment] 2017-11-22 21:47
@florianl but why tcpdump think it's 32256 bytes in length?

**Comment by florianl** [comment] 2017-11-23 20:48
32256 decimal is 0x7E00 and 0b111111000000000. I can't spot this bit sequence in your provided dump. I think, we can close this issue here.

**Closed** 2018-11-02 19:10 UTC
